version: "3"

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  node-server:
    image: node-server
    container_name: node-server
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
